import test from 'node:test'
import assert from 'node:assert/strict'
import { BoxGeometry } from 'three'
import { unzipSync, zipSync, strFromU8, strToU8 } from 'fflate'
import { parseOrcaGcodeStats, computeSlicerHpp } from '../utils/slicerHpp.js'
import { printGroupsTo3mfBuffer } from '../utils/keychainExport.js'
import { prepareSlicerInput, resolveOrcaInstall } from '../server/utils/orcaSlicer.js'

const gcode = `; generated by OrcaSlicer 2.4.2 on 2026-09-15
;TYPE:Prime tower
; filament used [g] = 2.07, 1.39, 1.20
; total filament used [g] = 4.65
; total filament change = 26
; estimated printing time (normal mode) = 26m 34s
`

test('Orca statistics use the total rather than summing rounded color slots', () => {
  const stats = parseOrcaGcodeStats(gcode)
  assert.equal(stats.totalGrams, 4.65)
  assert.equal(stats.printTimeSeconds, 1594)
  assert.equal(stats.filamentChanges, 26)
  assert.equal(stats.primeTower, true)
  assert.equal(stats.slicerVersion, '2.4.2')
  assert.equal(parseOrcaGcodeStats(gcode.replace('26m 34s', '1d 2h 3m 4s')).printTimeSeconds, 93784)
  assert.throws(() => parseOrcaGcodeStats('; no statistics'), /statistik/)
  assert.throws(() => parseOrcaGcodeStats(gcode.replace('4.65', '40')), /konsisten/)
})

test('sliced HPP charges machine time once and recalculates cost without reslicing', () => {
  const stats = parseOrcaGcodeStats(gcode)
  const hpp = computeSlicerHpp(stats)
  assert.deepEqual(hpp.breakdown, { materialCost: 930, failureBuffer: 47, electricityCost: 96, depreciationCost: 615, laborCost: 1667, packagingCost: 1000 })
  assert.equal(hpp.total, 4355)
  const updated = computeSlicerHpp(stats, { filamentPricePerKg: 100000, extraPartsCost: 1500 })
  assert.equal(updated.breakdown.materialCost, 1965)
  assert.equal(updated.breakdown.depreciationCost, 615)
  assert.equal(updated.breakdown.failureBuffer, 23)
  assert.equal(computeSlicerHpp(null), null)
  assert.throws(() => computeSlicerHpp(stats, { powerWatt: -1 }), /nol/)
  assert.throws(() => computeSlicerHpp(stats, { depreciationMonths: 0 }), /lebih dari nol/)
})

function generatorArchive() {
  const geometry = new BoxGeometry(10, 10, 2)
  try { return unzipSync(new Uint8Array(printGroupsTo3mfBuffer([{ name: 'Test', parts: [{ geometry, color: '#ffffff' }] }]))) }
  finally { geometry.dispose() }
}

test('API accepts only generator geometry and replaces uploaded executable settings', async () => {
  const zip = generatorArchive()
  zip['Metadata/project_settings.config'] = strToU8(JSON.stringify({ filament_colour: ['#ffffff'], post_process: ['dangerous-command'], machine_start_gcode: 'untrusted' }))
  const result = await prepareSlicerInput(zipSync(zip), 'keychain')
  assert.equal(result.settings.layer_height, '0.12')
  assert.equal(result.settings.post_process, undefined)
  assert.equal(result.settings.machine_start_gcode, undefined)
  const plain = await prepareSlicerInput(zipSync(zip), 'keychain', false)
  assert.equal(plain.settings.layer_height, undefined)
  zip['Metadata/model_settings.config'] = strToU8('<config><metadata key="post_process" value="dangerous-command"/></config>')
  await assert.rejects(() => prepareSlicerInput(zipSync(zip), 'keychain'), /objek/)
})

test('API rejects external resources, unexpected files and unsupported tools', async () => {
  const zip = generatorArchive()
  await assert.rejects(() => prepareSlicerInput(zipSync(zip), 'lightbox'), /Generator/)
  zip['evil.sh'] = strToU8('script')
  await assert.rejects(() => prepareSlicerInput(zipSync(zip), 'keychain'), /generator/)
  delete zip['evil.sh']
  zip['3D/3dmodel.model'] = strToU8(strFromU8(zip['3D/3dmodel.model']).replace('<resources>', '<resources><component path="../../secret"/>'))
  await assert.rejects(() => prepareSlicerInput(zipSync(zip), 'keychain'), /lokal/)
})

test('Mac default uses the app bundle Resources folder', () => {
  const { executable, profilesPath } = resolveOrcaInstall({ executable: '', profilesPath: '' })
  if (process.platform === 'darwin') {
    assert.equal(executable, '/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer')
    assert.equal(profilesPath, '/Applications/OrcaSlicer.app/Contents/Resources/profiles/Anycubic')
  } else if (process.platform === 'win32') {
    assert.match(executable, /orca-slicer\.exe$/i)
  } else {
    assert.equal(executable, '')
  }
})
