import { computeHpp } from './hpp.js'

// Editable assumptions for estimates when no material/machine has been recorded.
export const SLICER_COST_DEFAULTS = Object.freeze({
  filamentPricePerKg: 200000, powerWatt: 150, machinePrice: 5000000,
  depreciationMonths: 36, machineHoursPerMonth: 100, electricityRate: 1445,
  failurePercent: 5, laborMinutes: 5, laborRatePerHour: 20000,
  packagingCost: 1000, extraPartsCost: 0
})

export function computeSlicerHpp(slice, costs = SLICER_COST_DEFAULTS) {
  if (!slice || !Number.isFinite(slice.totalGrams) || slice.totalGrams <= 0 || !Number.isFinite(slice.printTimeSeconds) || slice.printTimeSeconds <= 0) return null
  const values = { ...SLICER_COST_DEFAULTS, ...costs }
  for (const [key, value] of Object.entries(values)) {
    if (!Number.isFinite(Number(value)) || Number(value) < 0) throw new Error('Biaya harus berupa angka nol atau lebih')
    values[key] = Number(value)
  }
  if (!values.depreciationMonths || !values.machineHoursPerMonth) throw new Error('Masa depresiasi dan jam pemakaian harus lebih dari nol')
  const hpp = computeHpp([{
    quantityUsed: slice.totalGrams,
    printTimeMinutes: slice.printTimeSeconds / 60,
    material: { name: 'PLA (perkiraan)', unit: 'gram', pricePerUnit: values.filamentPricePerKg / 1000 },
    machine: { powerWatt: values.powerWatt, purchasePrice: values.machinePrice, depreciationMonths: values.depreciationMonths },
    failureRatePercent: values.failurePercent, laborMinutes: values.laborMinutes, laborRatePerHour: values.laborRatePerHour
  }, {
    quantityUsed: 1, material: { name: 'Komponen tambahan', unit: 'set', pricePerUnit: values.extraPartsCost }
  }], [{ quantityUsed: 1, packaging: { name: 'Kemasan', pricePerUnit: values.packagingCost } }], {
    electricityRatePerKwh: values.electricityRate, machineUsageHoursPerMonth: values.machineHoursPerMonth
  })
  return { ...hpp, assumptions: values }
}

export function parseOrcaGcodeStats(gcode) {
  const number = (pattern) => {
    const value = gcode.match(pattern)?.[1]
    return value == null ? NaN : Number(value)
  }
  const totalGrams = number(/^; total filament used \[g\] = ([\d.]+)\s*$/m)
  const time = gcode.match(/^; estimated printing time \(normal mode\) = (.+)$/m)?.[1]?.trim()
  const units = { d: 86400, h: 3600, m: 60, s: 1 }
  let printTimeSeconds = 0
  for (const match of time?.matchAll(/(\d+(?:\.\d+)?)\s*([dhms])/g) || []) printTimeSeconds += Number(match[1]) * units[match[2]]
  const filamentGrams = (gcode.match(/^; filament used \[g\] = (.+)$/m)?.[1] || '').split(',').map((n) => Number(n.trim()))
  if (!Number.isFinite(totalGrams) || totalGrams <= 0 || !printTimeSeconds || !filamentGrams.length || filamentGrams.some((n) => !Number.isFinite(n) || n < 0)) {
    throw new Error('OrcaSlicer tidak menghasilkan statistik filament dan waktu cetak yang valid')
  }
  // Orca rounds each slot separately; use its total for HPP, not the rounded slot sum.
  if (Math.abs(filamentGrams.reduce((a, b) => a + b, 0) - totalGrams) > 0.02 * filamentGrams.length) throw new Error('Total pemakaian filament tidak konsisten')
  return {
    totalGrams, printTimeSeconds, filamentGrams,
    filamentChanges: number(/^; total filament change = (\d+)\s*$/m) || 0,
    primeTower: /^;TYPE:Prime tower\s*$/m.test(gcode),
    slicerVersion: gcode.match(/^; generated by OrcaSlicer ([\w.+-]+)/m)?.[1] || 'unknown'
  }
}
